<?php

namespace Tests\Unit\Http\Requests;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

/**
 * @see \App\Http\Requests\PersonStoreRequest
 */
class PersonStoreRequestTest extends TestCase
{
    /** @var \App\Http\Requests\PersonStoreRequest */
    private $subject;

    protected function setUp(): void
    {
        parent::setUp();

        $this->subject = new \App\Http\Requests\PersonStoreRequest();
    }

    /**
     * @test
     */
    public function authorize()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $actual = $this->subject->authorize();

        $this->assertTrue($actual);
    }

    /**
     * @test
     */
    public function rules()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $actual = $this->subject->rules();

        $this->assertValidationRules([
            'preferred_name' => 'string',
            'first_name' => 'required|string',
            'middle_name' => 'string',
            'last_name' => 'string',
            'title' => 'string',
            'suffix' => 'string',
            'professional_title' => 'string',
            'preferred_language' => 'string',
            'date_of_birth' => 'string',
            'person_type_id' => 'int',
        ], $actual);
    }

    // test cases...
}
